### ISSUE TITLE
不支持linux下运行

### ISSUE THREAD

**Issue by CrazyBoyM** [triwinds/ppocr-onnx#4]
在centos7.6 python3.7环境下，运行提示 := 语法错误
是否编码格式在类unix系统下有问题？
同样python版本windows11下测试可以运行。

**Comment by triwinds** [comment]
这个错误是因为 `:=` 是从 python 3.8 才开始支持的语法。

现在这个问题已经被修复，更新一下试试？

**Comment by CrazyBoyM** [comment]
ok, thanks!
