### ISSUE TITLE
耗时比较

### ISSUE THREAD

**Issue by cccusername** [triwinds/ppocr-onnx#5]
大佬，有测试过耗时吗，onnxruntime会比paddle推理快吗

**Comment by fuhengwu2021** [comment]
https://github.com/henrywoo/hiq/blob/main/hiq/examples/onnxruntime/ocr.md

**Comment by cccusername** [comment]
> https://github.com/henrywoo/hiq/blob/main/hiq/examples/onnxruntime/ocr.md

好的，谢谢

**Comment by IceHowe** [comment]
![image](https://github.com/user-attachments/assets/3e92f571-7268-4dcb-9c8f-6b38d837b6fb)
这部分没看懂，请问什么意思啊？gpu情况下onnx推理是比paddle快吗？大概快多少？
